### ISSUE TITLE
Make the menu dropdoen bigger if the text is larger

### ISSUE THREAD

**Issue by rlegge** [isabolic/apex-plg-dropdown-btn#11]
Hi, If the text on the dropdown menu is larger than the menu button, the text gets truncated. Please could it be changed so that the dropdown is large enough to show the dull dropdown menu text.

Many thanks
Richard

**Comment by isabolic** [comment]
done, check the new attibute "Menu width as btn" if false, the menu width is determinant based on list width

**Comment by isabolic** [comment]
packed in latest release 1.1.2
