### ISSUE TITLE
How to customize dropdown menu on apex 5.1

### ISSUE THREAD

**Issue by yecicen** [isabolic/apex-plg-dropdown-btn#17]
Hi, I was wondering that can we change the background color, items size etc. and How :?

I added the plugin and combined my 3 buttons into one. But  #button labels exceeding the dropdown size, and also looks ugly since there is no css I can apply. I added some css but only affected the button itself, not the dropdown menu.

**Comment by isabolic** [comment]
HI @yecicen 

you can apply css directly on a page, check the screenshot.

![image](https://user-images.githubusercontent.com/1404432/40610947-b0d54a82-6274-11e8-99d2-445ca90fe30a.png)
