### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by onlygecko** [isabolic/apex-plg-dropdown-btn#4]
Hi,

I saw Your plugin today on apex.world. This looks very promissing. Have You already thought about releasing it under a license so others users know whether and under which conditions they can use your plugin?

Kind regards,
Peter

**Comment by isabolic** [comment]
Hi Peter,

i have totally forgotten. I will do that. 

Best regards
isabolic99

**Comment by isabolic** [comment]
Done.

**Comment by onlygecko** [comment]
Thanks for using the MIT. :-)
