### ISSUE TITLE
Installation: Insufficient Right

### ISSUE THREAD

**Issue by onlygecko** [isabolic/apex-plg-dropdown-btn#6]
When I run _ax_plg_drop_down.pks_ I get the error message  

`ORA-01031 - insufficient privileges`

As which user (schema user?) needs the script to be run and which privileges does the user need?

Thanks for your help in advance.
Peter

**Comment by onlygecko** [comment]
My fault... The "PLAYGROUND" in the first line needs to be replaced.

**Comment by isabolic** [comment]
Hi, the is also a issue
