### ISSUE TITLE
Optimize installation process

### ISSUE THREAD

**Issue by onlygecko** [isabolic/apex-plg-dropdown-btn#8]
Is it possible to optimize the installation process. A good example is the select2 plugin for APEX (https://apex.oracle.com/pls/apex/f?p=64237:20). It is just one file that needs to be uploaded.

**Comment by isabolic** [comment]
There is a posobility to install plugin with one script. i'll look into that. Meanwhile please update you dropdown.button.js it was a fix for https://github.com/isabolic/apex-plg-dropdown-btn/issues/7

**Comment by isabolic** [comment]
installation process is updated to 2 step :
1) compile pks & pkb in apex parsing schema
2) run install script  in apex parsing schema
