### ISSUE TITLE
When button is on Interactive Report, buttons dropdown behind report

### ISSUE THREAD

**Issue by rlegge** [isabolic/apex-plg-dropdown-btn#9]
Using Universal Theme.

As above. If you click on the button, it drops down, but the menu items are hidden by the interactive report if the button has more than one menu item.

Rgds
Richard

**Comment by isabolic** [comment]
patch:
in dropdown.button.css:

.dropdown-menu-btn, 
.dropdown-menu-btn.t-Button:hover, 
.dropdown-menu-btn.a-Button:hover,
.dropdown-menu-btn.t-Button:active, 
.dropdown-menu-btn.a-Button:active{
  z-index: initial;
}

**Comment by rlegge** [comment]
Hi Ivan,

Ive just upgraded to the latest release..
- installed the new packages
- installed the new plugin
- uloaded the new button.css, button.js, handlebar

However Im encountering some issues.

Im getting    http://playground/ws/dropdown.button.css
net::ERR_NAME_NOT_RESOLVED  in the button.css, button.js and handlebars
v405.js  on load

then when I hover over the dropdown button I get the link shows up, but
when I click on a dropdown menu, nothing much happens.  Then I did get the
one error below.

dropdown.button.js:48 Uncaught TypeError: Cannot read property 'trigger' of
undefined(…)triggerEvent @ dropdown.button.js:48itemClick @
dropdown.button.js:69dispatch @ jquery-2.1.3.min.js?v=5.0.3.00.03:3r.handle
@ jquery-2.1.3.min.js?v=5.0.3.00.03:3

Id appreciate it if you could help, as its impacting our production system
now.

Kind Regards
Richard

**Comment by rlegge** [comment]
Hi Ivan,

Ive found that if I click very quickly on the dropdowns, they work. But if
I wait until the dropdown has completed it drop, then clicking on it
doesn't do anything..

rgds

**Comment by isabolic** [comment]
Hi rlegge,
can you create a example on https://apex.oracle.com/pls/apex/  ?

**Comment by isabolic** [comment]
also can you provide screenshots of your conf. properties on your plugin on that specific page?

**Comment by rlegge** [comment]
Hi Ivan,

Will do.

Also, using the plugin with 3 plugin buttons on my page adds about 2
seconds page load time. Do you know why this would be taking so long?

Kind Regards
Richard

**Comment by isabolic** [comment]
![image](https://cloud.githubusercontent.com/assets/1404432/19959841/9cc02ec8-a1a9-11e6-9c69-c836e3fbca58.png)

on my local machine the rendering time of plugin is 0.00291.. Can you check you apex page in debug mode to see execution time?

**Comment by rlegge** [comment]
my execution time is also low. (0.00984 )..  Maybe I need to start with a clean install. I upgraded based on your latest updates. I downgraded, I patch etc. so I need to clean the plugin out, and relead it.  Is it your belief that the code loaded here is all working OK?

**Comment by isabolic** [comment]
I think that loading issue is not from plugin.. in debug mode you can see what is taking long to execute..  
you can create a copy of a page and remove dropdown plugin, then see if IR report is still taking to long ..

**Comment by rlegge** [comment]
OK. Ive now created a test in apex. workspace is VRS login as test/test application 291 page 22

I did the following:

1) Upload the packages and run them
2) Installed the plugin
3) changed the references for CSS and JS in the plugin from  /playground.... /dropdown.button.css  to #PLUGIN_FILES#dropdown.button.css

Then added the button and plugin on the page.

Please note, the plugin is now also dropping down behind the interactive report again..  Also Im getting a different result on the other dropdown. item 1 works, but item2 doesn't?

Kind Regards
Richard

**Comment by isabolic** [comment]
Hi Richard,

can you provide the link? tnx

**Comment by rlegge** [comment]
https://apex.oracle.com/pls/apex/f?p=291:22:109338298882139:::::

**Comment by rlegge** [comment]
ahh. I changed the theme on the test app to responsive, and now I can reproduce the error where you can click very quickly on a menu option and it works, but doesnt after half a second or so..

**Comment by rlegge** [comment]
sorry. not responsive. universal...

**Comment by isabolic** [comment]
Hi Richard,

please upload latest dropdown.button.js into your example, and see that click event (alert("test2")) is triggering every time. 

Bug for non responsive theme dropdown is still left..

Best regards
isabolic99

**Comment by rlegge** [comment]
Hi Ivan, Appreciate all the work you are putting in here. Thanks.

Its all working now except when you click away from the dropdown, it doesn't close the button menu again.

also, tiny question. which setting do I change to make the dropdown open faster?

**Comment by isabolic** [comment]
Hi Richard,
please upload latest dropdown.button.js see if everthing is ok.
Regarding "open/close" faster i have set 200 miliseconds, if that is not good i can put in plugin config. so that developer can change this 200 ms.

**Comment by rlegge** [comment]
All seems to be working great now. And the dropdown speed is better. (faster.) Many Thanks indeed.

Rgds
Richard

**Comment by isabolic** [comment]
Hi Richard,

thank you for your feedback. I'm closing this issue..

Rgds
isabolic99
